# this is big heading

## this is small heading

## this is small heading1

## numpy standards numerical python
## It is used to mathematical and statistical caluclations

In [1]:
import numpy as np
# import is a keyword which is used to import all dependencies
# as is a keyword to provide alias name for your library

In [2]:
pip install numpy


[notice] A new release of pip is available: 23.1.2 -> 26.1.2
[notice] To update, run: C:\Users\ganga\AppData\Local\Programs\Python\Python311\python.exe -m pip install --upgrade pip


In [3]:
# List-- it is an advanced data type which is used to store List of elements
# it is denoted by using square brackets
# each elements is separated by comma
# it allows both homogeneous and heterogeneous elements
# list is mutable and it is changable

In [4]:
list1 = [10,20,30,40,50]
print(list1)

[10, 20, 30, 40, 50]


In [5]:
x =  list(range(10))
print(x)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [6]:
print(type(x))

<class 'list'>


In [7]:
y = tuple(range(1,11))
print(y)

(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)


In [8]:
print(type(y))

<class 'tuple'>


In [9]:
x = 10
print(type(x))

<class 'int'>


In [10]:
x1 = [10,10.5,10+2j,"palle",True]
print(type(x1))

<class 'list'>


In [11]:
list1 = [10,20,30,40]
print(list)

<class 'list'>


In [12]:
t1 = (10,20,30,40)
print(type(t1))

<class 'tuple'>


In [13]:
print(list(t1))

[10, 20, 30, 40]


# creating numpy arrays

## creating arrays using list

In [91]:
list1 = [10,20,30,40,50,60]
arr1 = np.array(list1)
print(arr1)

[10 20 30 40 50 60]


## creating array using tuple

In [15]:
tuple1 = (10,20,30,40,50)
arr2 = np.array(tuple1)
print(arr2)
print(type(arr2))

[10 20 30 40 50]
<class 'numpy.ndarray'>


# creating a numpy arrays using list and store float values

In [16]:
list2 = [10,20,30,40,50]
arr3 = np.array(list2,dtype=float)
print(arr3)

[10. 20. 30. 40. 50.]


In [17]:
list3 = [20,39,29,42,24,54]
arr4 = np.array(list3,dtype=bool)
print(arr4)

[ True  True  True  True  True  True]


# order of datatypes
# str,complex,float,int,bool

In [18]:
list4 = [10,20.5,30+3j,True,"palle"]
arr4  = np.array(list4)
print(arr4)

['10' '20.5' '(30+3j)' 'True' 'palle']


In [19]:
list4 = [10,20.5,30+3j,True]
arr4  = np.array(list4)
print(arr4)

[10. +0.j 20.5+0.j 30. +3.j  1. +0.j]


In [20]:
list4 = [10,20.5,True]
arr4  = np.array(list4)
print(arr4)

[10.  20.5  1. ]


In [21]:
list4 = [10,True]
arr4  = np.array(list4)
print(arr4)

[10  1]


In [22]:
list4 = [True]
arr4  = np.array(list4)
print(arr4)

[ True]


In [23]:
#set is mutable and set elements are immutable

In [24]:
c1 = {1,2,3}
c1.add(4)
print(c1)

{1, 2, 3, 4}


In [25]:
c2 = {10,20,30}
print(c2)

{10, 20, 30}


In [26]:
print(dir(c1))

['__and__', '__class__', '__class_getitem__', '__contains__', '__delattr__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__getstate__', '__gt__', '__hash__', '__iand__', '__init__', '__init_subclass__', '__ior__', '__isub__', '__iter__', '__ixor__', '__le__', '__len__', '__lt__', '__ne__', '__new__', '__or__', '__rand__', '__reduce__', '__reduce_ex__', '__repr__', '__ror__', '__rsub__', '__rxor__', '__setattr__', '__sizeof__', '__str__', '__sub__', '__subclasshook__', '__xor__', 'add', 'clear', 'copy', 'difference', 'difference_update', 'discard', 'intersection', 'intersection_update', 'isdisjoint', 'issubset', 'issuperset', 'pop', 'remove', 'symmetric_difference', 'symmetric_difference_update', 'union', 'update']


## generating the elements

In [27]:
r1 = list(range(1,10,2))
print(r1)

[1, 3, 5, 7, 9]


In [28]:
# r1 = list(range(1,10,0.5))
# print(r1)

In [29]:
arr5 = np.arange(1,10,0.5)
print(arr5)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [30]:
arr6 = np.linspace(1,10,10)
print(arr6)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [31]:
arr7 = np.arange(1,10,0.5)
print(arr7)

[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [32]:
arr7 = np.linspace(1,10,10,dtype=int)
print(arr7)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
arr8 = np.arange(1,10,0.5,dtype=int)
print(arr8)

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


In [34]:
print(int(1.5))

1


In [35]:
c1 = {}
print(type(c1))

<class 'dict'>


# creating 2D array using nested list

In [36]:
list6 = [[10,20,30,40],[50,60,70,80]]
arr6 = np.array(list6)
print(arr6)

[[10 20 30 40]
 [50 60 70 80]]


In [37]:
print(len(arr6))
print(arr6.ndim)
print(arr6.shape)
print(arr6.size)

2
2
(2, 4)
8


In [38]:
# x = 10
# print(len(x))

# creating 2d array using arange and reshape

In [39]:
arr7 = np.arange(1,10).reshape(3,3)
print(arr7)
print(arr7.ndim)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
2


In [40]:
arr8 = np.arange(1,11).reshape(5,2)
print(arr8)
print(arr8.ndim)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]]
2


# creating array using ndmin

In [41]:
arr9 = np.array([1,2,3,4,5],ndmin=3)
print(arr9)

[[[1 2 3 4 5]]]


# flattend the array

In [42]:
arr10 = np.array([[1,2],[3,4],[5,6]])
print(arr10)

[[1 2]
 [3 4]
 [5 6]]


In [43]:
print(arr10.flatten())

[1 2 3 4 5 6]


In [44]:
x = [10,20,30,40]
print(x[0])
print(x[0:1])

10
[10]


In [45]:
print(10 + 5)
print([10] + [5])

15
[10, 5]


## arthmetic operations

In [46]:
z1 = np.arange(1,5).reshape(2,2)
z2 = np.arange(1,5).reshape(2,2)

In [47]:
print(z1)
print(z2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [48]:
print(z1 + 5)

[[6 7]
 [8 9]]


In [49]:
print(z1 - 5)

[[-4 -3]
 [-2 -1]]


In [50]:
print(z1 * 5)

[[ 5 10]
 [15 20]]


In [51]:
print(z1 // 5)

[[0 0]
 [0 0]]


In [52]:
print(z1 / 5)

[[0.2 0.4]
 [0.6 0.8]]


In [53]:
print(z1 % 5)

[[1 2]
 [3 4]]


In [54]:
print(z1 ** 5)

[[   1   32]
 [ 243 1024]]


In [55]:
z3 = np.arange(1,6)
print(z3)

[1 2 3 4 5]


In [56]:
print(np.repeat(z3,5))

[1 1 1 1 1 2 2 2 2 2 3 3 3 3 3 4 4 4 4 4 5 5 5 5 5]


In [57]:
print(np.tile(z3,5))

[1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5 1 2 3 4 5]


In [58]:
# print([10,20,30] + 5)
# print([10,20,30] - 5)
print([10,20,30] * 5)
# print([10,20,30] // 5)

[10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30, 10, 20, 30]


In [59]:
print(z2 * 3)

[[ 3  6]
 [ 9 12]]


## Accessing array elements  

In [60]:
arr1 = np.arange(1,21).reshape(5,4)
print(arr1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [61]:
print(arr1[0])

[1 2 3 4]


In [62]:
print(arr1[-1])

[17 18 19 20]


In [63]:
print(arr1[2])

[ 9 10 11 12]


In [64]:
print(arr1[0][0])

1


In [65]:
print(arr1[0][::-1])

[4 3 2 1]


In [66]:
print(arr1[::-1])

[[17 18 19 20]
 [13 14 15 16]
 [ 9 10 11 12]
 [ 5  6  7  8]
 [ 1  2  3  4]]


In [67]:
print(arr1[0:2,0:2])

[[1 2]
 [5 6]]


In [68]:
print(arr1[0:5,0:2])

[[ 1  2]
 [ 5  6]
 [ 9 10]
 [13 14]
 [17 18]]


In [69]:
print(arr1[:,-1])

[ 4  8 12 16 20]


In [70]:
print(arr1[:,-1:-2:-1])

[[ 4]
 [ 8]
 [12]
 [16]
 [20]]


In [71]:
print(arr1[::-1,::-1])

[[20 19 18 17]
 [16 15 14 13]
 [12 11 10  9]
 [ 8  7  6  5]
 [ 4  3  2  1]]


# matrices

In [72]:
b1 = np.arange(1,5).reshape(2,2)
b2 = np.arange(1,5).reshape(2,2)

In [73]:
b1

array([[1, 2],
       [3, 4]])

In [74]:
b2

array([[1, 2],
       [3, 4]])

In [75]:
print(b1 * b2)

[[ 1  4]
 [ 9 16]]


In [76]:
print(np.dot(b1,b2))

[[ 7 10]
 [15 22]]


In [77]:
b1 = np.arange(1,3).reshape(1,2)
print(b1)

[[1 2]]


In [78]:
b2 = np.arange(1,3).reshape(2,1)
print(b2)

[[1]
 [2]]


In [79]:
print(np.dot(b1,b2))

[[5]]


# matrix rule: no.of in first matrix is equal too number of rows in second matrix

# built in functions to create matrices

In [80]:
m1 = np.zeros((3,3),dtype=int)
print(m1)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [81]:
m2 = np.ones((3,3),dtype=int)
print(m2)

[[1 1 1]
 [1 1 1]
 [1 1 1]]


In [82]:
m3 = np.full((3,3),5,dtype=int)
print(m3)

[[5 5 5]
 [5 5 5]
 [5 5 5]]


In [83]:
m4 = np.ones((3,3),dtype=int)*4
print(m4)

[[4 4 4]
 [4 4 4]
 [4 4 4]]


In [84]:
m5 = np.eye(3,dtype=int)
print(m5)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


# aggregate functions

In [85]:
arr1 = np.random.randint(1,50,15)
print(arr1)

[37 43 12 13 37 25 45  5 40 15 11 14 47 19 45]


In [86]:
print(np.min(arr1))
print(np.max(arr1))
print(np.argmin(arr1))
print(np.argmax(arr1))
print(np.mean(arr1))
print(np.median(arr1))

5
47
7
12
27.2
25.0


# joins

In [87]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)
print(arr1)
print(arr2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [88]:
print(np.concatenate((arr1,arr2),axis=0))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]


In [89]:
print(np.concatenate((arr1,arr2),axis=1))

[[1 2 3 1 2 3]
 [4 5 6 4 5 6]
 [7 8 9 7 8 9]]


In [90]:
print(np.concatenate((arr1,arr2)))

[[1 2 3]
 [4 5 6]
 [7 8 9]
 [1 2 3]
 [4 5 6]
 [7 8 9]]
